### ISSUE TITLE
Exercícios de Lógica

### ISSUE THREAD

**Issue by jardelima** [ThiagoDellaNoce/javascript4noobs#18]
Tenho uma lista de exercícios de lógica de programação bem legal aqui pra treinar Javascript. Posso criar uma pasta de exercícios e dar um Pull Resquest no projeto. 
( Desconsidere caso seja uma ideia sem nexo, pois é meu primeiro pull request e eu ainda estou aprendendo a usá-lo. Gostei da ideia desse repositório e quis ajudar. )

**Comment by ThiagoDellaNoce** [comment]
claro! cria ae e da o pull request! Vai ficar bastante legal! 
Obrigado por se interessar a ajudar.
