### ISSUE TITLE
Sugestão de link para exercícios.

### ISSUE THREAD

**Issue by gabrieldarezzo** [ThiagoDellaNoce/javascript4noobs#23]
Oq acha de linkar uma lista de exercícios? 

https://github.com/gabrieldarezzo/helpjs-ravi

Veja se pode agregar.

**Comment by ThiagoDellaNoce** [comment]
@jardelima Consegue dar uma olhada ae pra gnt?

**Comment by jardelima** [comment]
É um ótimo conteúdo! Podemos linkar no "read me" do repositório. Pode ser @ThiagoDellaNoce ?

**Comment by ThiagoDellaNoce** [comment]
pode sim! Faz lá pra gente por favor
