### ISSUE TITLE
Tópicos e nível de detalhamento

### ISSUE THREAD

**Issue by VitorGultzgoff** [ThiagoDellaNoce/javascript4noobs#6]
**Javascript** compreende uma gama de informação dividida entre dezenas de setores, qual será o **foco** do projeto ?

- Direcionar o desenvolvedor à construir **aplicações básicas**, utilizando desde o **gerenciamento de estado**, **seletores no DOM** para aplicar uma _dinâmica ao estilo_ baseado em manipulação do usuário na aplicação, **consumo de informações externas** e **mapeamento** de informações entre **estruturas** para reutilizar informação ?
- Detalhar a **estrutura da linguagem em tempo de execução**, impactando em uma _visão macro_ sobre o **Desempenho da renderização e Performance** ?
- Será abordado **tópico por contexto** com resumo e **aplicação prática simples**, algo parecido com **W3C** ? Portanto para nos diferenciarmos teríamos que utilizar exemplos práticos e bem formulados para facilitar na compreensão ?

Baseado nessa visão poderemos dimensionar o _tamanho do esforço_, compreender o **nível de detalhamento** dos exemplos necessários e consequentemente listar quais tópicos/módulos precisam ser trabalhados. Assim que fizermos esse alinhamento, conseguiremos **detalhar os módulos de uma maneira muitos mais intuitiva** e congruente entre tópicos.

**Comment by ThiagoDellaNoce** [comment]
A ideia do projeto é ser um _roadmap_ resumido do que é Javascript para o aluno que chegar aqui e **ter ideia do que é**, **o quão poderoso** e **oque ele precisa estudar a partir daqui**. Basicamente uma sinopse da linguagem.
