### ISSUE TITLE
Sugestão de Mudanças

### ISSUE THREAD

**Issue by JVictorV** [ThiagoDellaNoce/javascript4noobs#7]
2
  - 1 Resumo
    - O JS já tem até o ES11

4
  - 1 Funções de Saída
    - Abordar os outros métodos do console (warn, error, dir) por ex

  - 2 Cometários
    - Tem um "echo" no exemplo, mudar para console.log

  - 3 Tipos de dados primitivos
    - Faltou o BigInt e o Symbol
    - Tem um sequência com um trema no u
  
  - 5 Operadores aritméticos
    - Faltou abordar o --, ++, - antes de variavel e + antes de variável

  - 7 Condicionais
    - Acho válido colocar o IF ELSE antes de explicar ternário

  - 8 Estruturas de Repetição
    - Explicar sobre o break e o continue
    - Explicar a diferença entre o for in e o for of (https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Statements/for...of)

  - 9 Funções
    - (IMPORTANTE) Explicar sobre funções anônimas e a diferença no contexto (this e nome da função)
    - Colocar o "P" do 'para que isso?' do final maiúsculo

  - 10 Exceptions
    - Adicionar um exemplo de como o try catch funciona
    - Explicar como dar throw num Error()

5
  - 7 Event Listener
    - O nome vai continuar em inglês ou portugues? acho que esse conflito de hora estar em inglês ou português causa confusão
    - A explicação do que é um evento ta muito simples, achei confuso tmb

Não sei se eu to maluco mas em algum lugar eu tinha lido a relação de es6 com Ecmascript 2016 e tá errado, o ES6 é o ES2015

No mais acho valido explicar principalmente sobre promises, sobre alguns métodos do Array (map, filter, sort, find etc), spread operator e talvez sobre o this

Sei que o conteúdo é voltado pra iniciantes por isso os pontos em aberto, mas acho importante discutir essas coisas

**Comment by ThiagoDellaNoce** [comment]
Correções implementadas! 
Obrigado pelo apoio!
